In [1]:
pip install open3d==0.10.0

     |████████████████████████████████| 3.9 MB 8.9 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
import time
import open3d
import pandas as pd
import matplotlib.pyplot as plt

## USE http://www.open3d.org/docs/release/tutorial/Basic/

## CHALLENGE 1 - OPEN A FILE OF YOUR CHOICE AND VISUALIZE THE POINT CLOUD
# The supported extension names are: pcd, ply, xyz, xyzrgb, xyzn, pts.
pcd = open3d.io.read_point_cloud("/Users/GA/Downloads/tabletop_high_resolution/T-rex_high.pcd")
#print(np.asarray([pcd.points]))
open3d.visualization.draw_geometries([pcd])

In [2]:
print(np.asarray([pcd.points]))

[[[ -25.698986   -9.128601 -651.88208 ]
  [ -25.157757   -9.142601 -651.891724]
  [ -24.657757   -9.132828 -651.890564]
  ...
  [  -2.157757  -40.565598 -562.721008]
  [  -1.657757  -40.565598 -562.788147]
  [  -2.157757  -40.065598 -562.757935]]]


In [3]:
## CHALLENGE 2 - VOXEL GRID DOWNSAMPLING
print(f"Points between downsampling: {len(pcd.points)} ")
downpcd=pcd.voxel_down_sample(voxel_size=0.2)

print(f"Points after downsampling: {len(downpcd.points)}") 
open3d.visualization.draw_geometries([downpcd])

Points between downsampling: 176508 
Points after downsampling: 175906


In [4]:
## CHALLENGE 3 - SEGMENTATION
t1=time.time()
_, inliers = downpcd.segment_plane(distance_threshold=0.3,ransac_n=3,num_iterations=250)
inlier_cloud=downpcd.select_by_index(inliers)
outlier_cloud=downpcd.select_by_index(inliers,invert=True)
inlier_cloud.paint_uniform_color([1,0,0])
outlier_cloud.paint_uniform_color([0,0,1])
open3d.visualization.draw_geometries([inlier_cloud,outlier_cloud])
t2=time.time()
print(f"time_taken:{t2-t1}")

time_taken:5.330618143081665


In [5]:
# CHALLENGE 4 - CLUSTERING USING DBSCAN
with open3d.utility.VerbosityContextManager(open3d.utility.VerbosityLevel.Debug) as cm:
    labels = np.array(outlier_cloud.cluster_dbscan(eps=0.5,min_points=5,print_progress=True))

max_label=labels.max()
print(f"point cloud has {max_label+1} clusters")
colors=plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
colors[labels < 0] = 0
outlier_cloud.colors=open3d.utility.Vector2dVector(colors[:,:3])
open3d.visualization.draw_geometries([outlier_cloud])

[Open3D DEBUG] Precompute Neighbours
[Open3D DEBUG] Done Precompute Neighbours
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 304
point cloud has 304 clusters


RuntimeError: 

In [6]:
# BONUS CHALLENGE - CLUSTERING USING KDTREE AND KNN INSTEAD
pcd_tree = open3d.geometry.KDTreeFlann(outlier_cloud)
print("Paint the 15th point red.")
outlier_cloud.colors[15] = [1,0,0]
print("Find its 20 nearest neighbors, paint blue.")
[k,idx,_] = pcd_tree.search_knn_vector_3d(outlier_cloud.points[15],20)
np.asarray(outlier_cloud.colors)[idx[1:],:]=[0,0,1]
open3d.visualization.draw_geometries([outlier_cloud])

Paint the 15th point red.
Find its 20 nearest neighbors, paint blue.


In [7]:
# CHALLENGE 5 - BOUNDING BOXES IN 3D
obbs=[]
indexes=pd.Series(range(len(labels))).groupby(labels,sort=False).apply(list).tolist()

In [8]:
Max_Points = 1000
Min_Points = 20
clusters=[]
for i in range(0,len(indexes)):
    nb_pts=len(outlier_cloud.select_by_index(indexes[i]).points)
    if (nb_pts>Min_Points and nb_pts<Max_Points):
        sub_cloud=outlier_cloud.select_by_index(indexes[i])
        #clusters.append(sub_cloud)
        #print(np.asarray([sub_cloud.points]))
        obb=sub_cloud.get_axis_aligned_bounding_box()
        obb.color=(0,0,1)
        obbs.append(obb)

In [ ]:
list_of_visuals=[]
list_of_visuals.append(outlier_cloud)
list_of_visuals.extend(obbs)
list_of_visuals.append(inlier_cloud)
open3d.visualization.draw_geometries(list_of_visuals)

In [ ]:
print(len(list_of_visuals))
print(np.asarray([clusters]))